[package]
name = "evaporchain-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "evaporchain"
path = "src/main.rs"

[dependencies]
tokio = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
clap = { version = "4", features = ["derive"] }
reqwest = { version = "0.12", features = ["json"] }
colored = "2"
hex = { workspace = true }
libc = "0.2"
futures = "0.3"
evaporchain-types = { path = "../evaporchain-types" }
evaporchain-execution = { path = "../evaporchain-execution" }
evaporchain-crypto = { path = "../evaporchain-crypto" }
evaporchain-state = { path = "../evaporchain-state" }
