[package]
name = "evaporchain-script"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
hex = { workspace = true }
evaporchain-types = { path = "../evaporchain-types" }
evaporchain-allen-decay = { path = "../evaporchain-allen-decay" }
blake3 = "1"

[dev-dependencies]
proptest = "1"
