[package]
name = "evaporchain-crypto"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rand = { workspace = true }
hex = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
blake3 = "1"
sha2 = "0.10"
pasta_curves = "0.5"
pqc_dilithium = { version = "0.2", features = ["mode3"] }
blst = "0.3"
zeroize = { version = "1", features = ["derive"] }

[dev-dependencies]
proptest = "1"
