//! EvaporChain Wallet Library
//!
//! Post-quantum wallet for EvaporChain with:
//! - ML-DSA (FIPS 204) key generation and management
//! - AES-256-GCM encrypted keystore (password-protected)
//! - Address derivation from public keys (BLAKE3)
//! - Transaction construction and signing for all tx types
//! - Multi-account HD-style wallet support
//!
//! # Architecture
//!
//! ```text
//! Wallet
//! ├── KeyStore (encrypted on disk)
//! │   └── KeyPairEntry[] (name, address, encrypted ML-DSA keys)
//! ├── TxBuilder (construct + sign transactions)
//! └── AddressBook (named contacts)
//! ```

pub mod account;
pub mod address;
pub mod assets;
pub mod auto_refresh;
pub mod backup;
pub mod batch;
pub mod build_info;
pub mod cli;
pub mod config;
pub mod contacts;
pub mod doctor;
pub mod energy;
pub mod gas;
pub mod hints;
pub mod history;
pub mod keystore;
pub mod mnemonic;
pub mod nonce;
pub mod offline;
pub mod output;

pub mod access_control;
pub mod address_scoring;
pub mod addressbook_sync;
pub mod allowlist;
pub mod analytics;
pub mod anomaly_detector;
pub mod audit_log;
pub mod audit_trail;
pub mod batch_executor;
pub mod benchmark;
pub mod bridge;
pub mod cache_manager;
pub mod chain_indexer;
pub mod changelog;
pub mod circuit_breaker;
pub mod command_palette;
pub mod compliance_report;
pub mod config_validator;
pub mod contract_abi;
pub mod contract_deployer;
pub mod contract_verifier;
pub mod coverage_report;
pub mod cross_chain_swap;
pub mod dapp;
pub mod dca_engine;
pub mod debug_console;
pub mod delegation;
pub mod diagnostic;
pub mod energy_optimizer;
pub mod escrow;
pub mod event_bus;
pub mod export;
pub mod feature_flags;
pub mod fee_analytics;
pub mod fee_bumper;
pub mod fee_optimizer;
pub mod flash_loan;
pub mod fuzzer;
pub mod gas_profiler;
pub mod gas_station;
pub mod governance_dashboard;
pub mod hardware;
pub mod health;
pub mod help_system;
pub mod hooks;
pub mod i18n;
pub mod intent;
pub mod key_rotation;
pub mod labels;
pub mod limit_order;
pub mod liquidity_pool;
pub mod memo;
pub mod mempool_monitor;
pub mod metrics;
pub mod migrate;
pub mod multisig;
pub mod name_service;
pub mod network_health;
pub mod notification_rules;
pub mod notifications;
pub mod object_manager;
pub mod onboarding;
pub mod payment_stream;
pub mod peer_discovery;
pub mod permission_manager;
pub mod pipeline;
pub mod plugin;
pub mod pnl_tracker;
pub mod policy_engine;
pub mod portfolio_analytics;
pub mod portfolio_rebalance;
pub mod price_feed;
pub mod privacy_shield;
pub mod qr;
pub mod rate_limit;
pub mod recovery;
pub mod regression_tracker;
pub mod reputation;
pub mod retry;
pub mod rpc;
pub mod scheduler;
pub mod scripting;
pub mod secure_enclave;
pub mod session_keys;
pub mod shared_vault;
pub mod signer;
pub mod simulate;
pub mod smart_alerts;
pub mod snapshot;
pub mod social_recovery;
pub mod spending;
pub mod staking;
pub mod state_sync;
pub mod task_queue;
pub mod tax;
pub mod telemetry;
pub mod templates;
pub mod test_harness;
pub mod theme_engine;
pub mod threat_monitor;
pub mod timelock;
pub mod token_registry;
pub mod tx_builder;
pub mod tx_decoder;
pub mod tx_preview;
pub mod tx_receipt_store;
pub mod tx_simulator;
pub mod validation;
pub mod wallet_api;
pub mod wallet_connect;
pub mod wallet_migration;
pub mod watchonly;
pub mod watchtower;
pub mod whale_tracker;
pub mod ws_subscriber;
pub mod yield_farming;

pub use access_control::{AccessControlError, AccessController};
pub use account::{AccountError, AccountManager};
pub use address::{derive_address, format_address};
pub use address_scoring::{AddressScorer, AddressScoringError};
pub use addressbook_sync::{SyncError, SyncableAddressBook};
pub use allowlist::{AddressListStore, AllowlistError};
pub use analytics::{AnalyticsError, AnalyticsTracker};
pub use anomaly_detector::{AnomalyDetector, AnomalyDetectorError};
pub use assets::{AssetError, AssetManager};
pub use audit_log::{AuditError, AuditLog};
pub use audit_trail::{AuditTrail, AuditTrailError};
pub use auto_refresh::{AutoRefreshConfig, AutoRefresher};
pub use backup::BackupManager;
pub use batch_executor::{BatchExecutor, BatchExecutorError};
pub use benchmark::{BenchSuite, BenchmarkError};
pub use bridge::{BridgeError, BridgeManager};
pub use cache_manager::{CacheManager, CacheManagerError};
pub use chain_indexer::{ChainIndexer, IndexerError};
pub use changelog::{Changelog, ChangelogError};
pub use circuit_breaker::{CircuitBreakerError, CircuitBreakerManager};
pub use command_palette::{CommandPalette, CommandPaletteError};
pub use compliance_report::{ComplianceError, ComplianceManager};
pub use config::WalletConfig;
pub use config_validator::{ConfigValidator, ConfigValidatorError};
pub use contacts::{AddressBook, ContactError};
pub use contract_abi::{AbiStore, ContractAbiError};
pub use contract_deployer::{ContractDeployer, DeployerError};
pub use contract_verifier::{ContractVerifier, ContractVerifierError};
pub use coverage_report::{CoverageReportError, CoverageTracker};
pub use cross_chain_swap::{CrossChainError, CrossChainManager};
pub use dapp::{DappConnector, DappError};
pub use dca_engine::{DcaEngine, DcaError};
pub use debug_console::{DebugConsole, DebugConsoleError};
pub use delegation::{DelegationError, DelegationStore};
pub use diagnostic::{DiagnosticEngine, DiagnosticError};
pub use energy::EnergyMonitor;
pub use energy_optimizer::{EnergyOptimizer, EnergyOptimizerError};
pub use escrow::{EscrowError, EscrowManager};
pub use event_bus::{EventBus, EventBusError};
pub use export::{ExportError, Exporter};
pub use feature_flags::{FeatureFlagError, FeatureFlagManager};
pub use fee_analytics::{FeeAnalyticsError, FeeTracker};
pub use fee_bumper::{FeeBumper, FeeBumperError};
pub use fee_optimizer::{FeeOptimizer, FeeOptimizerError};
pub use flash_loan::{FlashLoanError, FlashLoanManager};
pub use fuzzer::{Fuzzer, FuzzerError};
pub use gas::{FeeEstimate, GasEstimator};
pub use gas_profiler::{GasProfiler, GasProfilerError};
pub use gas_station::{GasStation, GasStationError};
pub use governance_dashboard::{GovernanceDashboard, GovernanceError};
pub use hardware::{DeviceRegistry, HardwareError};
pub use health::{HealthChecker, HealthError};
pub use help_system::{HelpSystem, HelpSystemError};
pub use history::TxHistory;
pub use hooks::{HookError, HookRegistry};
pub use i18n::{I18n, I18nError, Locale, MsgKey};
pub use intent::{IntentEngine, IntentError};
pub use key_rotation::{KeyRotationError, KeyRotationManager};
pub use keystore::{KeyStore, KeyStoreError};
pub use labels::{LabelError, LabelStore};
pub use limit_order::{LimitOrderError, LimitOrderManager};
pub use liquidity_pool::{LiquidityPoolError, LiquidityPoolManager};
pub use memo::{MemoError, MemoStore};
pub use mempool_monitor::{MempoolError, MempoolMonitor};
pub use metrics::{MetricsError, MetricsRegistry};
pub use migrate::{MigrateError, Migrator};
pub use mnemonic::{Mnemonic, MnemonicBackup, MnemonicError};
pub use multisig::{MultisigError, MultisigStore};
pub use name_service::{NameService, NameServiceError};
pub use network_health::{NetworkHealthError, NetworkHealthMonitor};
pub use nonce::NonceManager;
pub use notification_rules::{NotificationRuleError, RuleEngine};
pub use notifications::{NotificationCenter, NotificationError};
pub use object_manager::{ObjectManager, ObjectManagerError};
pub use offline::{Broadcaster, OfflineSigner, SignedTransaction};
pub use onboarding::{OnboardingError, OnboardingManager};
pub use payment_stream::{PaymentStreamError, PaymentStreamManager};
pub use peer_discovery::{PeerDiscoveryError, PeerRegistry};
pub use permission_manager::{PermissionManager, PermissionManagerError};
pub use pipeline::{PipelineError, TxPipeline};
pub use plugin::{PluginError, PluginRegistry};
pub use pnl_tracker::{PnlError, PnlTracker};
pub use policy_engine::{PolicyEngine, PolicyError};
pub use portfolio_analytics::{PortfolioAnalytics, PortfolioAnalyticsError};
pub use portfolio_rebalance::{RebalanceError, RebalanceManager};
pub use price_feed::{PriceFeed, PriceFeedError};
pub use privacy_shield::{PrivacyShield, PrivacyShieldError};
pub use qr::{QrCode, QrError};
pub use rate_limit::RateLimiter;
pub use recovery::{RecoveryError, RecoveryStore};
pub use regression_tracker::{RegressionTracker, RegressionTrackerError};
pub use reputation::{ReputationError, ReputationStore};
pub use retry::RetryConfig;
pub use rpc::{RpcClient, RpcError};
pub use scheduler::{Scheduler, SchedulerError};
pub use scripting::ScriptExecutor;
pub use secure_enclave::{SecureEnclave, SecureEnclaveError};
pub use session_keys::{AbstractionError, AbstractionStore};
pub use shared_vault::{SharedVaultError, SharedVaultManager};
pub use signer::{SignerError, WalletSigner};
pub use simulate::{SimulationResult, Simulator};
pub use smart_alerts::{SmartAlertEngine, SmartAlertError};
pub use snapshot::{SnapshotError, SnapshotStore};
pub use social_recovery::{SocialRecoveryError, SocialRecoveryManager};
pub use spending::{SpendingError, SpendingPolicy};
pub use staking::{GovernanceManager, StakingManager};
pub use state_sync::{StateSyncError, StateSyncManager};
pub use task_queue::{TaskQueue, TaskQueueError};
pub use tax::{TaxError, TaxTracker};
pub use telemetry::{TelemetryError, TelemetryManager};
pub use templates::{TemplateError, TemplateStore};
pub use test_harness::{TestHarness, TestHarnessError};
pub use theme_engine::{ThemeEngine, ThemeEngineError};
pub use threat_monitor::{ThreatMonitor, ThreatMonitorError};
pub use timelock::{TimelockError, TimelockStore};
pub use token_registry::{TokenRegistry, TokenRegistryError};
pub use tx_builder::TxBuilder;
pub use tx_decoder::{TxDecoder, TxDecoderError};
pub use tx_preview::{TxPreviewError, TxPreviewer};
pub use tx_receipt_store::{TxReceiptError, TxReceiptStore};
pub use tx_simulator::{TxSimulator, TxSimulatorError};
pub use wallet_api::{WalletApi, WalletApiError};
pub use wallet_connect::{WalletConnectError, WalletConnectManager};
pub use wallet_migration::{MigrationError, WalletMigrator};
pub use watchonly::{WatchOnlyError, WatchStore};
pub use watchtower::{Watchtower, WatchtowerError};
pub use whale_tracker::{WhaleTracker, WhaleTrackerError};
pub use ws_subscriber::{WsSubscriber, WsSubscriberError};
pub use yield_farming::{YieldFarmManager, YieldFarmingError};
