//! EvaporChain Wallet Library
//!
//! Post-quantum wallet for EvaporChain with:
//! - ML-DSA (FIPS 204) key generation and management
//! - AES-256-GCM encrypted keystore (password-protected)
//! - Address derivation from public keys (BLAKE3)
//! - Transaction construction and signing for all tx types
//! - Multi-account HD-style wallet support
//!
//! # Architecture
//!
//! ```text
//! Wallet
//! ├── KeyStore (encrypted on disk)
//! │   └── KeyPairEntry[] (name, address, encrypted ML-DSA keys)
//! ├── TxBuilder (construct + sign transactions)
//! └── AddressBook (named contacts)
//! ```

pub mod account;
pub mod address;
pub mod build_info;
pub mod assets;
pub mod auto_refresh;
pub mod backup;
pub mod batch;
pub mod cli;
pub mod config;
pub mod contacts;
pub mod doctor;
pub mod energy;
pub mod gas;
pub mod hints;
pub mod history;
pub mod keystore;
pub mod mnemonic;
pub mod nonce;
pub mod offline;
pub mod output;

pub mod dapp;
pub mod fee_analytics;
pub mod fee_bumper;
pub mod hardware;
pub mod labels;
pub mod pipeline;
pub mod rate_limit;
pub mod retry;
pub mod rpc;
pub mod signer;
pub mod simulate;
pub mod spending;
pub mod staking;
pub mod multisig;
pub mod hooks;
pub mod analytics;
pub mod audit_log;
pub mod export;
pub mod i18n;
pub mod policy_engine;
pub mod tax;
pub mod notifications;
pub mod reputation;
pub mod templates;
pub mod watchtower;
pub mod session_keys;
pub mod bridge;
pub mod tx_builder;
pub mod validation;
pub mod scripting;
pub mod metrics;
pub mod migrate;
pub mod qr;
pub mod benchmark;
pub mod health;
pub mod plugin;
pub mod scheduler;
pub mod allowlist;
pub mod timelock;
pub mod memo;
pub mod recovery;
pub mod delegation;
pub mod addressbook_sync;
pub mod gas_station;
pub mod intent;
pub mod snapshot;
pub mod token_registry;
pub mod watchonly;
pub mod peer_discovery;
pub mod mempool_monitor;
pub mod chain_indexer;
pub mod network_health;
pub mod price_feed;
pub mod address_scoring;
pub mod tx_decoder;
pub mod notification_rules;
pub mod contract_abi;
pub mod name_service;
pub mod tx_preview;
pub mod wallet_connect;
pub mod privacy_shield;
pub mod key_rotation;
pub mod access_control;
pub mod threat_monitor;
pub mod liquidity_pool;
pub mod yield_farming;
pub mod cross_chain_swap;
pub mod flash_loan;
pub mod dca_engine;
pub mod limit_order;
pub mod portfolio_rebalance;
pub mod smart_alerts;
pub mod social_recovery;
pub mod shared_vault;
pub mod payment_stream;
pub mod escrow;
pub mod pnl_tracker;
pub mod portfolio_analytics;
pub mod compliance_report;
pub mod whale_tracker;
pub mod energy_optimizer;
pub mod object_manager;
pub mod contract_deployer;
pub mod governance_dashboard;
pub mod fee_optimizer;
pub mod batch_executor;
pub mod wallet_migration;
pub mod diagnostic;
pub mod ws_subscriber;
pub mod event_bus;
pub mod tx_receipt_store;
pub mod state_sync;
pub mod debug_console;
pub mod gas_profiler;
pub mod contract_verifier;
pub mod tx_simulator;
pub mod audit_trail;
pub mod anomaly_detector;
pub mod secure_enclave;
pub mod permission_manager;
pub mod theme_engine;
pub mod command_palette;
pub mod onboarding;
pub mod help_system;
pub mod circuit_breaker;
pub mod cache_manager;
pub mod config_validator;
pub mod task_queue;
pub mod changelog;
pub mod feature_flags;
pub mod telemetry;
pub mod wallet_api;
pub mod test_harness;
pub mod fuzzer;
pub mod regression_tracker;
pub mod coverage_report;

pub use account::{AccountManager, AccountError};
pub use assets::{AssetManager, AssetError};
pub use backup::BackupManager;
pub use config::WalletConfig;
pub use contacts::{AddressBook, ContactError};
pub use history::TxHistory;
pub use energy::EnergyMonitor;
pub use gas::{GasEstimator, FeeEstimate};
pub use nonce::NonceManager;
pub use offline::{OfflineSigner, SignedTransaction, Broadcaster};
pub use auto_refresh::{AutoRefresher, AutoRefreshConfig};
pub use rate_limit::RateLimiter;
pub use retry::RetryConfig;
pub use address::{derive_address, format_address};
pub use keystore::{KeyStore, KeyStoreError};
pub use mnemonic::{Mnemonic, MnemonicBackup, MnemonicError};
pub use pipeline::{TxPipeline, PipelineError};
pub use rpc::{RpcClient, RpcError};
pub use signer::{WalletSigner, SignerError};
pub use simulate::{Simulator, SimulationResult};
pub use spending::{SpendingPolicy, SpendingError};
pub use multisig::{MultisigStore, MultisigError};
pub use hooks::{HookRegistry, HookError};
pub use labels::{LabelStore, LabelError};
pub use fee_analytics::{FeeTracker, FeeAnalyticsError};
pub use hardware::{DeviceRegistry, HardwareError};
pub use dapp::{DappConnector, DappError};
pub use notifications::{NotificationCenter, NotificationError};
pub use session_keys::{AbstractionStore, AbstractionError};
pub use bridge::{BridgeManager, BridgeError};
pub use i18n::{I18n, Locale, MsgKey, I18nError};
pub use templates::{TemplateStore, TemplateError};
pub use analytics::{AnalyticsTracker, AnalyticsError};
pub use reputation::{ReputationStore, ReputationError};
pub use watchtower::{Watchtower, WatchtowerError};
pub use audit_log::{AuditLog, AuditError};
pub use tax::{TaxTracker, TaxError};
pub use policy_engine::{PolicyEngine, PolicyError};
pub use export::{Exporter, ExportError};
pub use staking::{StakingManager, GovernanceManager};
pub use tx_builder::TxBuilder;
pub use scripting::ScriptExecutor;
pub use metrics::{MetricsRegistry, MetricsError};
pub use migrate::{Migrator, MigrateError};
pub use qr::{QrCode, QrError};
pub use benchmark::{BenchSuite, BenchmarkError};
pub use health::{HealthChecker, HealthError};
pub use plugin::{PluginRegistry, PluginError};
pub use scheduler::{Scheduler, SchedulerError};
pub use allowlist::{AddressListStore, AllowlistError};
pub use timelock::{TimelockStore, TimelockError};
pub use memo::{MemoStore, MemoError};
pub use recovery::{RecoveryStore, RecoveryError};
pub use delegation::{DelegationStore, DelegationError};
pub use addressbook_sync::{SyncableAddressBook, SyncError};
pub use gas_station::{GasStation, GasStationError};
pub use intent::{IntentEngine, IntentError};
pub use token_registry::{TokenRegistry, TokenRegistryError};
pub use fee_bumper::{FeeBumper, FeeBumperError};
pub use snapshot::{SnapshotStore, SnapshotError};
pub use watchonly::{WatchStore, WatchOnlyError};
pub use peer_discovery::{PeerRegistry, PeerDiscoveryError};
pub use mempool_monitor::{MempoolMonitor, MempoolError};
pub use chain_indexer::{ChainIndexer, IndexerError};
pub use network_health::{NetworkHealthMonitor, NetworkHealthError};
pub use price_feed::{PriceFeed, PriceFeedError};
pub use address_scoring::{AddressScorer, AddressScoringError};
pub use tx_decoder::{TxDecoder, TxDecoderError};
pub use notification_rules::{RuleEngine, NotificationRuleError};
pub use contract_abi::{AbiStore, ContractAbiError};
pub use name_service::{NameService, NameServiceError};
pub use tx_preview::{TxPreviewer, TxPreviewError};
pub use wallet_connect::{WalletConnectManager, WalletConnectError};
pub use privacy_shield::{PrivacyShield, PrivacyShieldError};
pub use key_rotation::{KeyRotationManager, KeyRotationError};
pub use access_control::{AccessController, AccessControlError};
pub use threat_monitor::{ThreatMonitor, ThreatMonitorError};
pub use liquidity_pool::{LiquidityPoolManager, LiquidityPoolError};
pub use yield_farming::{YieldFarmManager, YieldFarmingError};
pub use cross_chain_swap::{CrossChainManager, CrossChainError};
pub use flash_loan::{FlashLoanManager, FlashLoanError};
pub use dca_engine::{DcaEngine, DcaError};
pub use limit_order::{LimitOrderManager, LimitOrderError};
pub use portfolio_rebalance::{RebalanceManager, RebalanceError};
pub use smart_alerts::{SmartAlertEngine, SmartAlertError};
pub use social_recovery::{SocialRecoveryManager, SocialRecoveryError};
pub use shared_vault::{SharedVaultManager, SharedVaultError};
pub use payment_stream::{PaymentStreamManager, PaymentStreamError};
pub use escrow::{EscrowManager, EscrowError};
pub use pnl_tracker::{PnlTracker, PnlError};
pub use portfolio_analytics::{PortfolioAnalytics, PortfolioAnalyticsError};
pub use compliance_report::{ComplianceManager, ComplianceError};
pub use whale_tracker::{WhaleTracker, WhaleTrackerError};
pub use energy_optimizer::{EnergyOptimizer, EnergyOptimizerError};
pub use object_manager::{ObjectManager, ObjectManagerError};
pub use contract_deployer::{ContractDeployer, DeployerError};
pub use governance_dashboard::{GovernanceDashboard, GovernanceError};
pub use fee_optimizer::{FeeOptimizer, FeeOptimizerError};
pub use batch_executor::{BatchExecutor, BatchExecutorError};
pub use wallet_migration::{WalletMigrator, MigrationError};
pub use diagnostic::{DiagnosticEngine, DiagnosticError};
pub use ws_subscriber::{WsSubscriber, WsSubscriberError};
pub use event_bus::{EventBus, EventBusError};
pub use tx_receipt_store::{TxReceiptStore, TxReceiptError};
pub use state_sync::{StateSyncManager, StateSyncError};
pub use debug_console::{DebugConsole, DebugConsoleError};
pub use gas_profiler::{GasProfiler, GasProfilerError};
pub use contract_verifier::{ContractVerifier, ContractVerifierError};
pub use tx_simulator::{TxSimulator, TxSimulatorError};
pub use audit_trail::{AuditTrail, AuditTrailError};
pub use anomaly_detector::{AnomalyDetector, AnomalyDetectorError};
pub use secure_enclave::{SecureEnclave, SecureEnclaveError};
pub use permission_manager::{PermissionManager, PermissionManagerError};
pub use theme_engine::{ThemeEngine, ThemeEngineError};
pub use command_palette::{CommandPalette, CommandPaletteError};
pub use onboarding::{OnboardingManager, OnboardingError};
pub use help_system::{HelpSystem, HelpSystemError};
pub use circuit_breaker::{CircuitBreakerManager, CircuitBreakerError};
pub use cache_manager::{CacheManager, CacheManagerError};
pub use config_validator::{ConfigValidator, ConfigValidatorError};
pub use task_queue::{TaskQueue, TaskQueueError};
pub use changelog::{Changelog, ChangelogError};
pub use feature_flags::{FeatureFlagManager, FeatureFlagError};
pub use telemetry::{TelemetryManager, TelemetryError};
pub use wallet_api::{WalletApi, WalletApiError};
pub use test_harness::{TestHarness, TestHarnessError};
pub use fuzzer::{Fuzzer, FuzzerError};
pub use regression_tracker::{RegressionTracker, RegressionTrackerError};
pub use coverage_report::{CoverageTracker, CoverageReportError};
