[package]
name = "evaporchain-execution"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
evaporchain-types = { path = "../evaporchain-types" }
evaporchain-state = { path = "../evaporchain-state" }
evaporchain-crypto = { path = "../evaporchain-crypto" }
evaporchain-contracts = { path = "../evaporchain-contracts" }
evaporchain-script = { path = "../evaporchain-script" }
evaporchain-proving = { path = "../evaporchain-proving" }
evaporchain-sharding = { path = "../evaporchain-sharding" }
evaporchain-energy-kernel = { path = "../evaporchain-energy-kernel" }
evaporchain-fee-controller = { path = "../evaporchain-fee-controller" }
evaporchain-sanov-slashing = { path = "../evaporchain-sanov-slashing" }
evaporchain-llsa = { path = "../evaporchain-llsa" }
evaporchain-epv = { path = "../evaporchain-epv" }
evaporchain-tombstone = { path = "../evaporchain-tombstone" }
evaporchain-mortis = { path = "../evaporchain-mortis" }
evaporchain-cmu-gate = { path = "../evaporchain-cmu-gate" }
evaporchain-tur-liveness = { path = "../evaporchain-tur-liveness" }
evaporchain-boltzmann-stake  = { path = "../evaporchain-boltzmann-stake" }
evaporchain-demurrage        = { path = "../evaporchain-demurrage" }
evaporchain-refresh-market   = { path = "../evaporchain-refresh-market" }
evaporchain-decay-lamport    = { path = "../evaporchain-decay-lamport" }
evaporchain-mera             = { path = "../evaporchain-mera" }
blake3 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
hex = { workspace = true }
rayon = "1.10"

[dev-dependencies]
proptest = "1"
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "throughput"
harness = false
