---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart evaporchain-node
  ansible.builtin.systemd:
    name: evaporchain-node
    state: restarted
    daemon_reload: true
