//! Braid-Group Sequencer Commitment.
//!
//! Per `research/INVENTION_STACK.md` §A1.4 (far-frontier ship-now):
//!
//! > **Braid-Group Sequencer Commitment** — Garside normal form;
//! > Dehornoy ordering. tx ordering = braid word in B_n with
//! > canonical Garside form. Cheap, unprecedented at L1.
//! > *Don't oversell as "anyonic"* — it's just braid-group commitment,
//! > no quantum required.
//!
//! ## What's the idea
//!
//! The braid group `B_n` is generated by `n − 1` elementary
//! crossings `σ_1, …, σ_{n-1}` subject to the relations
//!
//! ```text
//!   σ_i σ_j = σ_j σ_i           for |i − j| ≥ 2  (commuting)
//!   σ_i σ_{i+1} σ_i = σ_{i+1} σ_i σ_{i+1}        (braid relation)
//! ```
//!
//! A *braid word* is a sequence of `±σ_i` generators (positive or
//! inverse). Two braid words are equivalent iff they map to the same
//! element of `B_n`. **Garside normal form** is the unique
//! canonical representative of each equivalence class — so any
//! ordering of `n` transactions can be encoded as a braid word and
//! committed to via the hash of its Garside form.
//!
//! ## Substrate scope
//!
//! Full Garside normal form (Garside 1969 / Birman 1974) requires
//! computing the lcm/gcd in the lattice of positive braids — a
//! non-trivial algorithm. **Substrate ships a simplified canonical
//! form**: trivial cancellations (`σ_i σ_i^{-1} = identity`) +
//! commuting-rearrangement into a deterministic order. Sufficient
//! for downstream consumers that need *some* canonical commitment;
//! production swaps in full Garside.
//!
//! Two braid words equivalent under the substrate's reduction
//! produce the same commitment. Two words equivalent under the
//! *full* Garside relations may differ in the substrate (the braid
//! relation `σ_i σ_{i+1} σ_i = σ_{i+1} σ_i σ_{i+1}` is not yet
//! applied) — that's the documented gap.
//!
//! ## Module map
//!
//! - [`word`] — `BraidWord { generators: Vec<i32> }`. `+i` = `σ_i`,
//!   `-i` = `σ_i^{-1}`.
//! - [`reduce`] — substrate-quality canonical reduction.
//! - [`commit`] — `commit_braid(word) -> [u8; 32]` blake3 hash of
//!   the reduced form.

pub mod commit;
pub mod reduce;
pub mod word;

pub use commit::commit_braid;
pub use reduce::reduce_canonical;
pub use word::{BraidWord, WordError};
