[package]
name = "evaporchain-consensus"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
evaporchain-types = { path = "../evaporchain-types" }
evaporchain-state = { path = "../evaporchain-state" }
evaporchain-execution = { path = "../evaporchain-execution" }
evaporchain-script = { path = "../evaporchain-script" }
evaporchain-contracts = { path = "../evaporchain-contracts" }
evaporchain-crypto = { path = "../evaporchain-crypto" }
evaporchain-da = { path = "../evaporchain-da" }
evaporchain-sharding = { path = "../evaporchain-sharding" }
evaporchain-mortis = { path = "../evaporchain-mortis" }
evaporchain-light-cone = { path = "../evaporchain-light-cone" }
evaporchain-causal-cone = { path = "../evaporchain-causal-cone" }
evaporchain-energy-kernel = { path = "../evaporchain-energy-kernel" }
blake3 = "1"
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }
aes-gcm = "0.10"

[dev-dependencies]
tempfile = "3"
proptest = "1"
