[package]
name = "evaporchain-state"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
evaporchain-types = { path = "../evaporchain-types" }
evaporchain-crypto = { path = "../evaporchain-crypto" }
evaporchain-sentinel = { path = "../evaporchain-sentinel" }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
hex = { workspace = true }
rocksdb = { workspace = true }
bincode = { workspace = true }
blake3 = { workspace = true }
zstd = "0.13"

[dev-dependencies]
proptest = "1"
tempfile = "3"
serde_json = { workspace = true }
