[package]
name = "evaporchain-sharding"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
evaporchain-types = { path = "../evaporchain-types" }
serde = { workspace = true }
blake3 = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
