[package]
name = "evaporchain-node"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
prove = ["evaporchain-proving/nova"]

[dependencies]
evaporchain-types = { path = "../evaporchain-types" }
evaporchain-crypto = { path = "../evaporchain-crypto" }
evaporchain-state = { path = "../evaporchain-state" }
evaporchain-consensus = { path = "../evaporchain-consensus" }
evaporchain-execution = { path = "../evaporchain-execution" }
evaporchain-proving = { path = "../evaporchain-proving" }
evaporchain-network = { path = "../evaporchain-network" }
evaporchain-da = { path = "../evaporchain-da" }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
rand = { workspace = true }
hex = { workspace = true }
axum = "0.7"
axum-extra = { version = "0.9", features = ["typed-header"] }
tower-http = { version = "0.5", features = ["cors", "fs"] }
tower = "0.4"
rusqlite = { version = "0.31", features = ["bundled"] }
bcrypt = "0.15"
chrono = { version = "0.4", features = ["serde"] }
blake3 = "1"
rocksdb = { workspace = true }
bincode = { workspace = true }
