[package]
name = "evaporchain-node"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
prove = ["evaporchain-proving/nova"]
test-utils = ["evaporchain-proving/test-utils"]

[[bench]]
name = "core_benchmarks"
harness = false

[dependencies]
evaporchain-types = { path = "../evaporchain-types" }
evaporchain-crypto = { path = "../evaporchain-crypto" }
evaporchain-state = { path = "../evaporchain-state" }
evaporchain-consensus = { path = "../evaporchain-consensus" }
evaporchain-execution = { path = "../evaporchain-execution" }
evaporchain-proving = { path = "../evaporchain-proving", features = ["test-utils"] }
evaporchain-network = { path = "../evaporchain-network" }
evaporchain-da = { path = "../evaporchain-da" }
evaporchain-script = { path = "../evaporchain-script" }
evaporchain-contracts = { path = "../evaporchain-contracts" }
evaporchain-sharding = { path = "../evaporchain-sharding" }
evaporchain-oracle = { path = "../evaporchain-oracle" }
evaporchain-hbct = { path = "../evaporchain-hbct" }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
rand = { workspace = true }
hex = { workspace = true }
axum = { version = "0.7", features = ["ws"] }
axum-extra = { version = "0.9", features = ["typed-header"] }
tower-http = { version = "0.5", features = ["cors", "fs"] }
tower = "0.4"
rusqlite = { version = "0.31", features = ["bundled"] }
bcrypt = "0.15"
chrono = { version = "0.4", features = ["serde"] }
blake3 = "1"
chacha20poly1305 = "0.10"
rocksdb = { workspace = true }
bincode = { workspace = true }
futures = "0.3"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
